services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  postgres:
    image: postgres:16
    env_file:
      - .env 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      - postgres
  api:
    build: ./api
    ports:
      - "5000:5000"
    env_file:
      - ./api/.env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
      - keycloak

volumes:
  mongo_data:
  keycloak_data: