services:

  # ---------------------------------
  # MONGODB
  # ---------------------------------

  mongo:

    image: mongo:7

    container_name: mongo

    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    networks:
      - medical_network


  # ---------------------------------
  # API FLASK
  # ---------------------------------

  api:

    build: ./api

    container_name: medical_api

    restart: always

    ports:
      - "5000:5000"

    env_file:
      - ./api/.env

    environment:

      MONGO_HOST: mongodb://mongo:27017

      JWT_SECRET: super_secret_jwt_key

    volumes:
      - ./uploads:/app/uploads

    depends_on:
      - mongo

    networks:
      - medical_network


# ---------------------------------
# VOLUMES
# ---------------------------------

volumes:

  mongo_data:


# ---------------------------------
# NETWORK
# ---------------------------------

networks:

  medical_network: